name: creolala
favicon: null
layout_spectrum: 0.1455034390091896
typography_spectrum: 0.7705903314054012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9239385698456317
  lightness: 0.2779395224060863
  saturation: 0.03409955697134137
  rhythmicContrast: 0.9699973985552788
purpose: []
